wandb_version: 1

batch_size:
  value: 32
class_weight:
  value: 0.1
cluster_margin:
  value: 1
cluster_weight:
  value: 0.05
d_model:
  value: 128
dropout:
  value: 0.2
encoder_layers:
  value: 2
eval_every:
  value: 5
lr:
  value: 0.0001
noise_std:
  value: 0.01
num_workers:
  value: 0
projection_dim:
  value: 32
tactile_weight:
  value: 0.2
temperature:
  value: 0.07
time_mask_ratio:
  value: 0.02
weight_decay:
  value: 0.0001
