set(_CATKIN_CURRENT_PACKAGE "bhand")
set(bhand_VERSION "1.0.0")
set(bhand_MAINTAINER "Wonikrobotics-git <wonikrobotics@gmail.com>")
set(bhand_PACKAGE_FORMAT "1")
set(bhand_BUILD_DEPENDS )
set(bhand_BUILD_EXPORT_DEPENDS )
set(bhand_BUILDTOOL_DEPENDS "catkin")
set(bhand_BUILDTOOL_EXPORT_DEPENDS )
set(bhand_EXEC_DEPENDS )
set(bhand_RUN_DEPENDS )
set(bhand_TEST_DEPENDS )
set(bhand_DOC_DEPENDS )
set(bhand_URL_WEBSITE "https://www.allegrohand.com/, https://github.com/Wonikrobotics-git/")
set(bhand_URL_BUGTRACKER "")
set(bhand_URL_REPOSITORY "")
set(bhand_DEPRECATED "")