set(_CATKIN_CURRENT_PACKAGE "py_node_exec")
set(py_node_exec_VERSION "0.0.0")
set(py_node_exec_MAINTAINER "takahisaueno <takahisaueno@fuji.waseda.jp>")
set(py_node_exec_PACKAGE_FORMAT "2")
set(py_node_exec_BUILD_DEPENDS "rospy")
set(py_node_exec_BUILD_EXPORT_DEPENDS "rospy")
set(py_node_exec_BUILDTOOL_DEPENDS "catkin")
set(py_node_exec_BUILDTOOL_EXPORT_DEPENDS )
set(py_node_exec_EXEC_DEPENDS "rospy")
set(py_node_exec_RUN_DEPENDS "rospy")
set(py_node_exec_TEST_DEPENDS )
set(py_node_exec_DOC_DEPENDS )
set(py_node_exec_URL_WEBSITE "")
set(py_node_exec_URL_BUGTRACKER "")
set(py_node_exec_URL_REPOSITORY "")
set(py_node_exec_DEPRECATED "")