set(_CATKIN_CURRENT_PACKAGE "allegro_hand_description")
set(allegro_hand_description_VERSION "1.0.0")
set(allegro_hand_description_MAINTAINER "Wonikrobotics-git <wonikrobotics@gmail.com>")
set(allegro_hand_description_PACKAGE_FORMAT "1")
set(allegro_hand_description_BUILD_DEPENDS )
set(allegro_hand_description_BUILD_EXPORT_DEPENDS )
set(allegro_hand_description_BUILDTOOL_DEPENDS "catkin")
set(allegro_hand_description_BUILDTOOL_EXPORT_DEPENDS )
set(allegro_hand_description_EXEC_DEPENDS )
set(allegro_hand_description_RUN_DEPENDS )
set(allegro_hand_description_TEST_DEPENDS )
set(allegro_hand_description_DOC_DEPENDS )
set(allegro_hand_description_URL_WEBSITE "https://www.allegrohand.com/, https://github.com/Wonikrobotics-git/")
set(allegro_hand_description_URL_BUGTRACKER "")
set(allegro_hand_description_URL_REPOSITORY "")
set(allegro_hand_description_DEPRECATED "")