set(_CATKIN_CURRENT_PACKAGE "allegro_hand_controllers")
set(allegro_hand_controllers_VERSION "1.0.0")
set(allegro_hand_controllers_MAINTAINER "Wonikrobotics-git <wonikrobotics@gmail.com>")
set(allegro_hand_controllers_PACKAGE_FORMAT "1")
set(allegro_hand_controllers_BUILD_DEPENDS "allegro_hand_driver" "bhand" "libpcan" "roscpp" "sensor_msgs")
set(allegro_hand_controllers_BUILD_EXPORT_DEPENDS "allegro_hand_description" "allegro_hand_driver" "allegro_hand_parameters" "bhand" "joint_state_publisher" "libpcan" "robot_state_publisher" "roscpp" "sensor_msgs" "xacro")
set(allegro_hand_controllers_BUILDTOOL_DEPENDS "catkin")
set(allegro_hand_controllers_BUILDTOOL_EXPORT_DEPENDS )
set(allegro_hand_controllers_EXEC_DEPENDS "allegro_hand_description" "allegro_hand_driver" "allegro_hand_parameters" "bhand" "joint_state_publisher" "libpcan" "robot_state_publisher" "roscpp" "sensor_msgs" "xacro")
set(allegro_hand_controllers_RUN_DEPENDS "allegro_hand_description" "allegro_hand_driver" "allegro_hand_parameters" "bhand" "joint_state_publisher" "libpcan" "robot_state_publisher" "roscpp" "sensor_msgs" "xacro")
set(allegro_hand_controllers_TEST_DEPENDS )
set(allegro_hand_controllers_DOC_DEPENDS )
set(allegro_hand_controllers_URL_WEBSITE "https://www.allegrohand.com/, https://github.com/Wonikrobotics-git/")
set(allegro_hand_controllers_URL_BUGTRACKER "")
set(allegro_hand_controllers_URL_REPOSITORY "")
set(allegro_hand_controllers_DEPRECATED "")