wandb_version: 1

batch_size:
  value: 8
d_model:
  value: 256
dropout:
  value: 0
encoder_layers:
  value: 4
lr:
  value: 0.0003
max_seq_len:
  value: 640
rec_dim:
  value: 256
sequence_length:
  value: 400
temperature:
  value: 0.1
