set(_CATKIN_CURRENT_PACKAGE "allegro_hand_python")
set(allegro_hand_python_VERSION "1.0.0")
set(allegro_hand_python_MAINTAINER "Wonikrobotics-git <wonikrobotics@gmail.com>")
set(allegro_hand_python_PACKAGE_FORMAT "1")
set(allegro_hand_python_BUILD_DEPENDS "rospy" "rostest")
set(allegro_hand_python_BUILD_EXPORT_DEPENDS "allegro_hand_controllers" "allegro_hand_description" "allegro_hand_driver" "allegro_hand_keyboard" "rospy" "rostest")
set(allegro_hand_python_BUILDTOOL_DEPENDS "catkin")
set(allegro_hand_python_BUILDTOOL_EXPORT_DEPENDS )
set(allegro_hand_python_EXEC_DEPENDS "allegro_hand_controllers" "allegro_hand_description" "allegro_hand_driver" "allegro_hand_keyboard" "rospy" "rostest")
set(allegro_hand_python_RUN_DEPENDS "allegro_hand_controllers" "allegro_hand_description" "allegro_hand_driver" "allegro_hand_keyboard" "rospy" "rostest")
set(allegro_hand_python_TEST_DEPENDS )
set(allegro_hand_python_DOC_DEPENDS )
set(allegro_hand_python_URL_WEBSITE "https://www.allegrohand.com/, https://github.com/Wonikrobotics-git/")
set(allegro_hand_python_URL_BUGTRACKER "")
set(allegro_hand_python_URL_REPOSITORY "")
set(allegro_hand_python_DEPRECATED "")