set(_CATKIN_CURRENT_PACKAGE "xela_server_ros")
set(xela_server_ros_VERSION "1.5.0")
set(xela_server_ros_MAINTAINER "Matt <matthias@xelarobotics.com>")
set(xela_server_ros_PACKAGE_FORMAT "3")
set(xela_server_ros_BUILD_DEPENDS "rospy" "std_msgs" "geometry_msgs" "message_generation")
set(xela_server_ros_BUILD_EXPORT_DEPENDS "rospy" "std_msgs" "geometry_msgs" "message_generation")
set(xela_server_ros_BUILDTOOL_DEPENDS "catkin")
set(xela_server_ros_BUILDTOOL_EXPORT_DEPENDS )
set(xela_server_ros_EXEC_DEPENDS "rospy" "std_msgs" "geometry_msgs" "message_runtime")
set(xela_server_ros_RUN_DEPENDS "rospy" "std_msgs" "geometry_msgs" "message_runtime" "message_generation")
set(xela_server_ros_TEST_DEPENDS )
set(xela_server_ros_DOC_DEPENDS )
set(xela_server_ros_URL_WEBSITE "http://xelarobotics.com")
set(xela_server_ros_URL_BUGTRACKER "")
set(xela_server_ros_URL_REPOSITORY "")
set(xela_server_ros_DEPRECATED "")