wandb_version: 1

batch_size:
  value: 8
dropout:
  value: 0
lr:
  value: 3.678284393404905e-05
rec_dim:
  value: 512
sequence_length:
  value: 400
temporal_blocks:
  value: 4
temporal_kernel_size:
  value: 5
