set(_CATKIN_CURRENT_PACKAGE "allegro_package")
set(allegro_package_VERSION "0.0.0")
set(allegro_package_MAINTAINER "takahisaueno <takahisaueno@fuji.waseda.jp>")
set(allegro_package_PACKAGE_FORMAT "2")
set(allegro_package_BUILD_DEPENDS "rospy" "sensor_msgs")
set(allegro_package_BUILD_EXPORT_DEPENDS "rospy" "sensor_msgs")
set(allegro_package_BUILDTOOL_DEPENDS "catkin")
set(allegro_package_BUILDTOOL_EXPORT_DEPENDS )
set(allegro_package_EXEC_DEPENDS "rospy" "sensor_msgs")
set(allegro_package_RUN_DEPENDS "rospy" "sensor_msgs")
set(allegro_package_TEST_DEPENDS )
set(allegro_package_DOC_DEPENDS )
set(allegro_package_URL_WEBSITE "")
set(allegro_package_URL_BUGTRACKER "")
set(allegro_package_URL_REPOSITORY "")
set(allegro_package_DEPRECATED "")