# CMake generated Testfile for 
# Source directory: /home/handlingteam2/HASA/ros_ws/src/allegro_hand_packages/allegro_hand_python
# Build directory: /home/handlingteam2/HASA/ros_ws/build-vscode/allegro_hand_packages/allegro_hand_python
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(_ctest_allegro_hand_python_nosetests_scripts.allegro_hand "/home/handlingteam2/HASA/ros_ws/build-vscode/catkin_generated/env_cached.sh" "/usr/bin/python3" "/opt/ros/noetic/share/catkin/cmake/test/run_tests.py" "/home/handlingteam2/HASA/ros_ws/build-vscode/test_results/allegro_hand_python/nosetests-scripts.allegro_hand.xml" "--return-code" "\"/usr/bin/cmake\" -E make_directory /home/handlingteam2/HASA/ros_ws/build-vscode/test_results/allegro_hand_python" "/usr/bin/nosetests3 -P --process-timeout=60 --where=/home/handlingteam2/HASA/ros_ws/src/allegro_hand_packages/allegro_hand_python/scripts/allegro_hand --with-xunit --xunit-file=/home/handlingteam2/HASA/ros_ws/build-vscode/test_results/allegro_hand_python/nosetests-scripts.allegro_hand.xml")
set_tests_properties(_ctest_allegro_hand_python_nosetests_scripts.allegro_hand PROPERTIES  _BACKTRACE_TRIPLES "/opt/ros/noetic/share/catkin/cmake/test/tests.cmake;160;add_test;/opt/ros/noetic/share/catkin/cmake/test/nosetests.cmake;83;catkin_run_tests_target;/home/handlingteam2/HASA/ros_ws/src/allegro_hand_packages/allegro_hand_python/CMakeLists.txt;18;catkin_add_nosetests;/home/handlingteam2/HASA/ros_ws/src/allegro_hand_packages/allegro_hand_python/CMakeLists.txt;0;")
add_test(_ctest_allegro_hand_python_rostest_launch_test_allegro_launch.test "/home/handlingteam2/HASA/ros_ws/build-vscode/catkin_generated/env_cached.sh" "/usr/bin/python3" "/opt/ros/noetic/share/catkin/cmake/test/run_tests.py" "/home/handlingteam2/HASA/ros_ws/build-vscode/test_results/allegro_hand_python/rostest-launch_test_allegro_launch.xml" "--return-code" "/usr/bin/python3 /opt/ros/noetic/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/handlingteam2/HASA/ros_ws/src/allegro_hand_packages/allegro_hand_python --package=allegro_hand_python --results-filename launch_test_allegro_launch.xml --results-base-dir \"/home/handlingteam2/HASA/ros_ws/build-vscode/test_results\" /home/handlingteam2/HASA/ros_ws/src/allegro_hand_packages/allegro_hand_python/launch_test/allegro_launch.test ")
set_tests_properties(_ctest_allegro_hand_python_rostest_launch_test_allegro_launch.test PROPERTIES  _BACKTRACE_TRIPLES "/opt/ros/noetic/share/catkin/cmake/test/tests.cmake;160;add_test;/opt/ros/noetic/share/rostest/cmake/rostest-extras.cmake;52;catkin_run_tests_target;/home/handlingteam2/HASA/ros_ws/src/allegro_hand_packages/allegro_hand_python/CMakeLists.txt;19;add_rostest;/home/handlingteam2/HASA/ros_ws/src/allegro_hand_packages/allegro_hand_python/CMakeLists.txt;0;")
