wandb_version: 1

batch_size:
  value: 8
dropout:
  value: 0
lr:
  value: 4.0e-05
rec_dim:
  value: 512
sequence_length:
  value: 400
tactile_derivative_weight:
  value: 1.5
tactile_highpass_weight:
  value: 1.5
tactile_mae_weight:
  value: 2
tactile_middle_tip:
  value: 1.5
tactile_topk_weight:
  value: 0.5
temporal_blocks:
  value: 6
temporal_kernel_size:
  value: 5
