wandb_version: 1

batch_size:
  value: 128
class_weight:
  value: 0.2
d_model:
  value: 128
dropout:
  value: 0.1
encoder_layers:
  value: 2
eval_every:
  value: 10
lr:
  value: 0.0003
noise_std:
  value: 0.01
projection_dim:
  value: 32
temperature:
  value: 0.1
time_mask_ratio:
  value: 0.08
weight_decay:
  value: 0
