set(_CATKIN_CURRENT_PACKAGE "xela_py")
set(xela_py_VERSION "0.0.0")
set(xela_py_MAINTAINER "takahisaueno <takahisaueno@fuji.waseda.jp>")
set(xela_py_PACKAGE_FORMAT "2")
set(xela_py_BUILD_DEPENDS "rospy" "xela_server_ros")
set(xela_py_BUILD_EXPORT_DEPENDS "rospy" "xela_server_ros")
set(xela_py_BUILDTOOL_DEPENDS "catkin")
set(xela_py_BUILDTOOL_EXPORT_DEPENDS )
set(xela_py_EXEC_DEPENDS "rospy" "xela_server_ros")
set(xela_py_RUN_DEPENDS "rospy" "xela_server_ros")
set(xela_py_TEST_DEPENDS )
set(xela_py_DOC_DEPENDS )
set(xela_py_URL_WEBSITE "")
set(xela_py_URL_BUGTRACKER "")
set(xela_py_URL_REPOSITORY "")
set(xela_py_DEPRECATED "")