_wandb:
    value:
        cli_version: 0.21.1
        e:
            sxzf4il314n7fkc8ugscs49awq9af926:
                args:
                    - -mode
                    - sweep
                    - -param_file
                    - parameter/selftouch_fcn_pos/parameter_base/parameter_base.yaml
                codePath: main.py
                codePathLocal: main.py
                cpu_count: 20
                cpu_count_logical: 28
                cudaVersion: "12.9"
                disk:
                    /:
                        total: "3886873042944"
                        used: "421544161280"
                email: hasa.handresearch@gmail.com
                executable: /usr/bin/python3
                gpu: NVIDIA GeForce RTX 4070 Ti SUPER
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 8448
                      memoryTotal: "17171480576"
                      name: NVIDIA GeForce RTX 4070 Ti SUPER
                      uuid: GPU-da011486-efc9-c376-7791-9825a6a181ef
                host: handlingteam2
                memory:
                    total: "33343229952"
                os: Linux-5.15.0-139-generic-x86_64-with-glibc2.29
                program: main.py
                python: CPython 3.8.10
                root: /root/motionlearning
                startedAt: "2026-07-02T14:50:53.476715Z"
                writerId: sxzf4il314n7fkc8ugscs49awq9af926
        m: []
        python_version: 3.8.10
        t:
            "1":
                - 1
                - 41
            "2":
                - 1
                - 5
                - 41
                - 53
            "3":
                - 2
                - 15
                - 16
            "4": 3.8.10
            "5": 0.21.1
            "12": 0.21.1
            "13": linux-x86_64
batch_size:
    value: 16
combo_dim:
    value: 3
decoder_dim:
    value: 256
decoder_out_dim:
    value: 256
dropout:
    value: "0.04"
early_stop_enabled:
    value: false
encoder_dim:
    value: 192
hidden_dim:
    value: 256
lr:
    value: "0.0002"
num_epochs:
    value: 500
phase_dim:
    value: 10
rec_dim:
    value: 256
temporal_blocks:
    value: 6
temporal_dilations:
    value:
        - 1
        - 2
        - 4
        - 8
        - 16
        - 1
temporal_kernel_size:
    value: 9
use_combo_condition:
    value: true
use_mean_residual_head:
    value: true
use_phase_condition:
    value: true
use_pos_temporal_deltas:
    value: true
